/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProtectedLayoutImport } from './routes/_protected/layout'
import { Route as AuthLayoutImport } from './routes/_auth/layout'
import { Route as UnprotectedIndexImport } from './routes/_unprotected/index'
import { Route as UnprotectedTermsAndConditionImport } from './routes/_unprotected/terms-and-condition'
import { Route as UnprotectedPrivacyPolicyImport } from './routes/_unprotected/privacy-policy'
import { Route as ProtectedNotificationsImport } from './routes/_protected/notifications'
import { Route as ProtectedMessagesImport } from './routes/_protected/messages'
import { Route as ProtectedDashboardImport } from './routes/_protected/dashboard'
import { Route as ProtectedCustomersImport } from './routes/_protected/customers'
import { Route as AuthVerifyEmailImport } from './routes/_auth/verify-email'
import { Route as AuthRegisterImport } from './routes/_auth/register'
import { Route as AuthLoginImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordImport } from './routes/_auth/forgot-password'
import { Route as AuthConfirmPasswordImport } from './routes/_auth/confirm-password'
import { Route as ProtectedSettingsLayoutImport } from './routes/_protected/settings/layout'
import { Route as ProtectedSettingsIndexImport } from './routes/_protected/settings/index'
import { Route as ProtectedCoursesIndexImport } from './routes/_protected/courses/index'
import { Route as ProtectedAnalyticsIndexImport } from './routes/_protected/analytics/index'
import { Route as ProtectedSettingsNotificationsImport } from './routes/_protected/settings/notifications'
import { Route as ProtectedSettingsDisplayImport } from './routes/_protected/settings/display'
import { Route as ProtectedSettingsAppearanceImport } from './routes/_protected/settings/appearance'
import { Route as ProtectedSettingsAccountImport } from './routes/_protected/settings/account'
import { Route as ProtectedCoursesAddImport } from './routes/_protected/courses/add'
import { Route as ProtectedCoursesSlugImport } from './routes/_protected/courses/$slug'
import { Route as ProtectedAnalyticsSlugImport } from './routes/_protected/analytics/$slug'
import { Route as ProtectedCoursesEditIndexImport } from './routes/_protected/courses/edit/index'
import { Route as ProtectedCoursesEditSlugImport } from './routes/_protected/courses/edit/$slug'

// Create/Update Routes

const ProtectedLayoutRoute = ProtectedLayoutImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const AuthLayoutRoute = AuthLayoutImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const UnprotectedIndexRoute = UnprotectedIndexImport.update({
  id: '/_unprotected/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UnprotectedTermsAndConditionRoute =
  UnprotectedTermsAndConditionImport.update({
    id: '/_unprotected/terms-and-condition',
    path: '/terms-and-condition',
    getParentRoute: () => rootRoute,
  } as any)

const UnprotectedPrivacyPolicyRoute = UnprotectedPrivacyPolicyImport.update({
  id: '/_unprotected/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedNotificationsRoute = ProtectedNotificationsImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

const ProtectedMessagesRoute = ProtectedMessagesImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

const ProtectedDashboardRoute = ProtectedDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

const ProtectedCustomersRoute = ProtectedCustomersImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

const AuthVerifyEmailRoute = AuthVerifyEmailImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthConfirmPasswordRoute = AuthConfirmPasswordImport.update({
  id: '/confirm-password',
  path: '/confirm-password',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const ProtectedSettingsLayoutRoute = ProtectedSettingsLayoutImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

const ProtectedSettingsIndexRoute = ProtectedSettingsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedSettingsLayoutRoute,
} as any)

const ProtectedCoursesIndexRoute = ProtectedCoursesIndexImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

const ProtectedAnalyticsIndexRoute = ProtectedAnalyticsIndexImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

const ProtectedSettingsNotificationsRoute =
  ProtectedSettingsNotificationsImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => ProtectedSettingsLayoutRoute,
  } as any)

const ProtectedSettingsDisplayRoute = ProtectedSettingsDisplayImport.update({
  id: '/display',
  path: '/display',
  getParentRoute: () => ProtectedSettingsLayoutRoute,
} as any)

const ProtectedSettingsAppearanceRoute =
  ProtectedSettingsAppearanceImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => ProtectedSettingsLayoutRoute,
  } as any)

const ProtectedSettingsAccountRoute = ProtectedSettingsAccountImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ProtectedSettingsLayoutRoute,
} as any)

const ProtectedCoursesAddRoute = ProtectedCoursesAddImport.update({
  id: '/courses/add',
  path: '/courses/add',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

const ProtectedCoursesSlugRoute = ProtectedCoursesSlugImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

const ProtectedAnalyticsSlugRoute = ProtectedAnalyticsSlugImport.update({
  id: '/analytics/$slug',
  path: '/analytics/$slug',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

const ProtectedCoursesEditIndexRoute = ProtectedCoursesEditIndexImport.update({
  id: '/courses/edit/',
  path: '/courses/edit/',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

const ProtectedCoursesEditSlugRoute = ProtectedCoursesEditSlugImport.update({
  id: '/courses/edit/$slug',
  path: '/courses/edit/$slug',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsLayoutImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_auth/confirm-password': {
      id: '/_auth/confirm-password'
      path: '/confirm-password'
      fullPath: '/confirm-password'
      preLoaderRoute: typeof AuthConfirmPasswordImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_protected/customers': {
      id: '/_protected/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof ProtectedCustomersImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_protected/messages': {
      id: '/_protected/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof ProtectedMessagesImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_protected/notifications': {
      id: '/_protected/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof ProtectedNotificationsImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_unprotected/privacy-policy': {
      id: '/_unprotected/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof UnprotectedPrivacyPolicyImport
      parentRoute: typeof rootRoute
    }
    '/_unprotected/terms-and-condition': {
      id: '/_unprotected/terms-and-condition'
      path: '/terms-and-condition'
      fullPath: '/terms-and-condition'
      preLoaderRoute: typeof UnprotectedTermsAndConditionImport
      parentRoute: typeof rootRoute
    }
    '/_unprotected/': {
      id: '/_unprotected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof UnprotectedIndexImport
      parentRoute: typeof rootRoute
    }
    '/_protected/analytics/$slug': {
      id: '/_protected/analytics/$slug'
      path: '/analytics/$slug'
      fullPath: '/analytics/$slug'
      preLoaderRoute: typeof ProtectedAnalyticsSlugImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_protected/courses/$slug': {
      id: '/_protected/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof ProtectedCoursesSlugImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_protected/courses/add': {
      id: '/_protected/courses/add'
      path: '/courses/add'
      fullPath: '/courses/add'
      preLoaderRoute: typeof ProtectedCoursesAddImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_protected/settings/account': {
      id: '/_protected/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof ProtectedSettingsAccountImport
      parentRoute: typeof ProtectedSettingsLayoutImport
    }
    '/_protected/settings/appearance': {
      id: '/_protected/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof ProtectedSettingsAppearanceImport
      parentRoute: typeof ProtectedSettingsLayoutImport
    }
    '/_protected/settings/display': {
      id: '/_protected/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof ProtectedSettingsDisplayImport
      parentRoute: typeof ProtectedSettingsLayoutImport
    }
    '/_protected/settings/notifications': {
      id: '/_protected/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof ProtectedSettingsNotificationsImport
      parentRoute: typeof ProtectedSettingsLayoutImport
    }
    '/_protected/analytics/': {
      id: '/_protected/analytics/'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof ProtectedAnalyticsIndexImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_protected/courses/': {
      id: '/_protected/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof ProtectedCoursesIndexImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_protected/settings/': {
      id: '/_protected/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof ProtectedSettingsIndexImport
      parentRoute: typeof ProtectedSettingsLayoutImport
    }
    '/_protected/courses/edit/$slug': {
      id: '/_protected/courses/edit/$slug'
      path: '/courses/edit/$slug'
      fullPath: '/courses/edit/$slug'
      preLoaderRoute: typeof ProtectedCoursesEditSlugImport
      parentRoute: typeof ProtectedLayoutImport
    }
    '/_protected/courses/edit/': {
      id: '/_protected/courses/edit/'
      path: '/courses/edit'
      fullPath: '/courses/edit'
      preLoaderRoute: typeof ProtectedCoursesEditIndexImport
      parentRoute: typeof ProtectedLayoutImport
    }
  }
}

// Create and export the route tree

interface AuthLayoutRouteChildren {
  AuthConfirmPasswordRoute: typeof AuthConfirmPasswordRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthLayoutRouteChildren: AuthLayoutRouteChildren = {
  AuthConfirmPasswordRoute: AuthConfirmPasswordRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthLayoutRouteWithChildren = AuthLayoutRoute._addFileChildren(
  AuthLayoutRouteChildren,
)

interface ProtectedSettingsLayoutRouteChildren {
  ProtectedSettingsAccountRoute: typeof ProtectedSettingsAccountRoute
  ProtectedSettingsAppearanceRoute: typeof ProtectedSettingsAppearanceRoute
  ProtectedSettingsDisplayRoute: typeof ProtectedSettingsDisplayRoute
  ProtectedSettingsNotificationsRoute: typeof ProtectedSettingsNotificationsRoute
  ProtectedSettingsIndexRoute: typeof ProtectedSettingsIndexRoute
}

const ProtectedSettingsLayoutRouteChildren: ProtectedSettingsLayoutRouteChildren =
  {
    ProtectedSettingsAccountRoute: ProtectedSettingsAccountRoute,
    ProtectedSettingsAppearanceRoute: ProtectedSettingsAppearanceRoute,
    ProtectedSettingsDisplayRoute: ProtectedSettingsDisplayRoute,
    ProtectedSettingsNotificationsRoute: ProtectedSettingsNotificationsRoute,
    ProtectedSettingsIndexRoute: ProtectedSettingsIndexRoute,
  }

const ProtectedSettingsLayoutRouteWithChildren =
  ProtectedSettingsLayoutRoute._addFileChildren(
    ProtectedSettingsLayoutRouteChildren,
  )

interface ProtectedLayoutRouteChildren {
  ProtectedSettingsLayoutRoute: typeof ProtectedSettingsLayoutRouteWithChildren
  ProtectedCustomersRoute: typeof ProtectedCustomersRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedMessagesRoute: typeof ProtectedMessagesRoute
  ProtectedNotificationsRoute: typeof ProtectedNotificationsRoute
  ProtectedAnalyticsSlugRoute: typeof ProtectedAnalyticsSlugRoute
  ProtectedCoursesSlugRoute: typeof ProtectedCoursesSlugRoute
  ProtectedCoursesAddRoute: typeof ProtectedCoursesAddRoute
  ProtectedAnalyticsIndexRoute: typeof ProtectedAnalyticsIndexRoute
  ProtectedCoursesIndexRoute: typeof ProtectedCoursesIndexRoute
  ProtectedCoursesEditSlugRoute: typeof ProtectedCoursesEditSlugRoute
  ProtectedCoursesEditIndexRoute: typeof ProtectedCoursesEditIndexRoute
}

const ProtectedLayoutRouteChildren: ProtectedLayoutRouteChildren = {
  ProtectedSettingsLayoutRoute: ProtectedSettingsLayoutRouteWithChildren,
  ProtectedCustomersRoute: ProtectedCustomersRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedMessagesRoute: ProtectedMessagesRoute,
  ProtectedNotificationsRoute: ProtectedNotificationsRoute,
  ProtectedAnalyticsSlugRoute: ProtectedAnalyticsSlugRoute,
  ProtectedCoursesSlugRoute: ProtectedCoursesSlugRoute,
  ProtectedCoursesAddRoute: ProtectedCoursesAddRoute,
  ProtectedAnalyticsIndexRoute: ProtectedAnalyticsIndexRoute,
  ProtectedCoursesIndexRoute: ProtectedCoursesIndexRoute,
  ProtectedCoursesEditSlugRoute: ProtectedCoursesEditSlugRoute,
  ProtectedCoursesEditIndexRoute: ProtectedCoursesEditIndexRoute,
}

const ProtectedLayoutRouteWithChildren = ProtectedLayoutRoute._addFileChildren(
  ProtectedLayoutRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof ProtectedLayoutRouteWithChildren
  '/settings': typeof ProtectedSettingsLayoutRouteWithChildren
  '/confirm-password': typeof AuthConfirmPasswordRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/customers': typeof ProtectedCustomersRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/messages': typeof ProtectedMessagesRoute
  '/notifications': typeof ProtectedNotificationsRoute
  '/privacy-policy': typeof UnprotectedPrivacyPolicyRoute
  '/terms-and-condition': typeof UnprotectedTermsAndConditionRoute
  '/': typeof UnprotectedIndexRoute
  '/analytics/$slug': typeof ProtectedAnalyticsSlugRoute
  '/courses/$slug': typeof ProtectedCoursesSlugRoute
  '/courses/add': typeof ProtectedCoursesAddRoute
  '/settings/account': typeof ProtectedSettingsAccountRoute
  '/settings/appearance': typeof ProtectedSettingsAppearanceRoute
  '/settings/display': typeof ProtectedSettingsDisplayRoute
  '/settings/notifications': typeof ProtectedSettingsNotificationsRoute
  '/analytics': typeof ProtectedAnalyticsIndexRoute
  '/courses': typeof ProtectedCoursesIndexRoute
  '/settings/': typeof ProtectedSettingsIndexRoute
  '/courses/edit/$slug': typeof ProtectedCoursesEditSlugRoute
  '/courses/edit': typeof ProtectedCoursesEditIndexRoute
}

export interface FileRoutesByTo {
  '': typeof ProtectedLayoutRouteWithChildren
  '/confirm-password': typeof AuthConfirmPasswordRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/customers': typeof ProtectedCustomersRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/messages': typeof ProtectedMessagesRoute
  '/notifications': typeof ProtectedNotificationsRoute
  '/privacy-policy': typeof UnprotectedPrivacyPolicyRoute
  '/terms-and-condition': typeof UnprotectedTermsAndConditionRoute
  '/': typeof UnprotectedIndexRoute
  '/analytics/$slug': typeof ProtectedAnalyticsSlugRoute
  '/courses/$slug': typeof ProtectedCoursesSlugRoute
  '/courses/add': typeof ProtectedCoursesAddRoute
  '/settings/account': typeof ProtectedSettingsAccountRoute
  '/settings/appearance': typeof ProtectedSettingsAppearanceRoute
  '/settings/display': typeof ProtectedSettingsDisplayRoute
  '/settings/notifications': typeof ProtectedSettingsNotificationsRoute
  '/analytics': typeof ProtectedAnalyticsIndexRoute
  '/courses': typeof ProtectedCoursesIndexRoute
  '/settings': typeof ProtectedSettingsIndexRoute
  '/courses/edit/$slug': typeof ProtectedCoursesEditSlugRoute
  '/courses/edit': typeof ProtectedCoursesEditIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthLayoutRouteWithChildren
  '/_protected': typeof ProtectedLayoutRouteWithChildren
  '/_protected/settings': typeof ProtectedSettingsLayoutRouteWithChildren
  '/_auth/confirm-password': typeof AuthConfirmPasswordRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_protected/customers': typeof ProtectedCustomersRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/messages': typeof ProtectedMessagesRoute
  '/_protected/notifications': typeof ProtectedNotificationsRoute
  '/_unprotected/privacy-policy': typeof UnprotectedPrivacyPolicyRoute
  '/_unprotected/terms-and-condition': typeof UnprotectedTermsAndConditionRoute
  '/_unprotected/': typeof UnprotectedIndexRoute
  '/_protected/analytics/$slug': typeof ProtectedAnalyticsSlugRoute
  '/_protected/courses/$slug': typeof ProtectedCoursesSlugRoute
  '/_protected/courses/add': typeof ProtectedCoursesAddRoute
  '/_protected/settings/account': typeof ProtectedSettingsAccountRoute
  '/_protected/settings/appearance': typeof ProtectedSettingsAppearanceRoute
  '/_protected/settings/display': typeof ProtectedSettingsDisplayRoute
  '/_protected/settings/notifications': typeof ProtectedSettingsNotificationsRoute
  '/_protected/analytics/': typeof ProtectedAnalyticsIndexRoute
  '/_protected/courses/': typeof ProtectedCoursesIndexRoute
  '/_protected/settings/': typeof ProtectedSettingsIndexRoute
  '/_protected/courses/edit/$slug': typeof ProtectedCoursesEditSlugRoute
  '/_protected/courses/edit/': typeof ProtectedCoursesEditIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/settings'
    | '/confirm-password'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/customers'
    | '/dashboard'
    | '/messages'
    | '/notifications'
    | '/privacy-policy'
    | '/terms-and-condition'
    | '/'
    | '/analytics/$slug'
    | '/courses/$slug'
    | '/courses/add'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/analytics'
    | '/courses'
    | '/settings/'
    | '/courses/edit/$slug'
    | '/courses/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/confirm-password'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/customers'
    | '/dashboard'
    | '/messages'
    | '/notifications'
    | '/privacy-policy'
    | '/terms-and-condition'
    | '/'
    | '/analytics/$slug'
    | '/courses/$slug'
    | '/courses/add'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/analytics'
    | '/courses'
    | '/settings'
    | '/courses/edit/$slug'
    | '/courses/edit'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_protected/settings'
    | '/_auth/confirm-password'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/verify-email'
    | '/_protected/customers'
    | '/_protected/dashboard'
    | '/_protected/messages'
    | '/_protected/notifications'
    | '/_unprotected/privacy-policy'
    | '/_unprotected/terms-and-condition'
    | '/_unprotected/'
    | '/_protected/analytics/$slug'
    | '/_protected/courses/$slug'
    | '/_protected/courses/add'
    | '/_protected/settings/account'
    | '/_protected/settings/appearance'
    | '/_protected/settings/display'
    | '/_protected/settings/notifications'
    | '/_protected/analytics/'
    | '/_protected/courses/'
    | '/_protected/settings/'
    | '/_protected/courses/edit/$slug'
    | '/_protected/courses/edit/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthLayoutRoute: typeof AuthLayoutRouteWithChildren
  ProtectedLayoutRoute: typeof ProtectedLayoutRouteWithChildren
  UnprotectedPrivacyPolicyRoute: typeof UnprotectedPrivacyPolicyRoute
  UnprotectedTermsAndConditionRoute: typeof UnprotectedTermsAndConditionRoute
  UnprotectedIndexRoute: typeof UnprotectedIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthLayoutRoute: AuthLayoutRouteWithChildren,
  ProtectedLayoutRoute: ProtectedLayoutRouteWithChildren,
  UnprotectedPrivacyPolicyRoute: UnprotectedPrivacyPolicyRoute,
  UnprotectedTermsAndConditionRoute: UnprotectedTermsAndConditionRoute,
  UnprotectedIndexRoute: UnprotectedIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_protected",
        "/_unprotected/privacy-policy",
        "/_unprotected/terms-and-condition",
        "/_unprotected/"
      ]
    },
    "/_auth": {
      "filePath": "_auth/layout.tsx",
      "children": [
        "/_auth/confirm-password",
        "/_auth/forgot-password",
        "/_auth/login",
        "/_auth/register",
        "/_auth/verify-email"
      ]
    },
    "/_protected": {
      "filePath": "_protected/layout.tsx",
      "children": [
        "/_protected/settings",
        "/_protected/customers",
        "/_protected/dashboard",
        "/_protected/messages",
        "/_protected/notifications",
        "/_protected/analytics/$slug",
        "/_protected/courses/$slug",
        "/_protected/courses/add",
        "/_protected/analytics/",
        "/_protected/courses/",
        "/_protected/courses/edit/$slug",
        "/_protected/courses/edit/"
      ]
    },
    "/_protected/settings": {
      "filePath": "_protected/settings/layout.tsx",
      "parent": "/_protected",
      "children": [
        "/_protected/settings/account",
        "/_protected/settings/appearance",
        "/_protected/settings/display",
        "/_protected/settings/notifications",
        "/_protected/settings/"
      ]
    },
    "/_auth/confirm-password": {
      "filePath": "_auth/confirm-password.tsx",
      "parent": "/_auth"
    },
    "/_auth/forgot-password": {
      "filePath": "_auth/forgot-password.tsx",
      "parent": "/_auth"
    },
    "/_auth/login": {
      "filePath": "_auth/login.tsx",
      "parent": "/_auth"
    },
    "/_auth/register": {
      "filePath": "_auth/register.tsx",
      "parent": "/_auth"
    },
    "/_auth/verify-email": {
      "filePath": "_auth/verify-email.tsx",
      "parent": "/_auth"
    },
    "/_protected/customers": {
      "filePath": "_protected/customers.tsx",
      "parent": "/_protected"
    },
    "/_protected/dashboard": {
      "filePath": "_protected/dashboard.tsx",
      "parent": "/_protected"
    },
    "/_protected/messages": {
      "filePath": "_protected/messages.tsx",
      "parent": "/_protected"
    },
    "/_protected/notifications": {
      "filePath": "_protected/notifications.tsx",
      "parent": "/_protected"
    },
    "/_unprotected/privacy-policy": {
      "filePath": "_unprotected/privacy-policy.tsx"
    },
    "/_unprotected/terms-and-condition": {
      "filePath": "_unprotected/terms-and-condition.tsx"
    },
    "/_unprotected/": {
      "filePath": "_unprotected/index.tsx"
    },
    "/_protected/analytics/$slug": {
      "filePath": "_protected/analytics/$slug.tsx",
      "parent": "/_protected"
    },
    "/_protected/courses/$slug": {
      "filePath": "_protected/courses/$slug.tsx",
      "parent": "/_protected"
    },
    "/_protected/courses/add": {
      "filePath": "_protected/courses/add.tsx",
      "parent": "/_protected"
    },
    "/_protected/settings/account": {
      "filePath": "_protected/settings/account.tsx",
      "parent": "/_protected/settings"
    },
    "/_protected/settings/appearance": {
      "filePath": "_protected/settings/appearance.tsx",
      "parent": "/_protected/settings"
    },
    "/_protected/settings/display": {
      "filePath": "_protected/settings/display.tsx",
      "parent": "/_protected/settings"
    },
    "/_protected/settings/notifications": {
      "filePath": "_protected/settings/notifications.tsx",
      "parent": "/_protected/settings"
    },
    "/_protected/analytics/": {
      "filePath": "_protected/analytics/index.tsx",
      "parent": "/_protected"
    },
    "/_protected/courses/": {
      "filePath": "_protected/courses/index.tsx",
      "parent": "/_protected"
    },
    "/_protected/settings/": {
      "filePath": "_protected/settings/index.tsx",
      "parent": "/_protected/settings"
    },
    "/_protected/courses/edit/$slug": {
      "filePath": "_protected/courses/edit/$slug.tsx",
      "parent": "/_protected"
    },
    "/_protected/courses/edit/": {
      "filePath": "_protected/courses/edit/index.tsx",
      "parent": "/_protected"
    }
  }
}
ROUTE_MANIFEST_END */
