/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UnprotectedImport } from './routes/_unprotected'
import { Route as ProtectedImport } from './routes/_protected'
import { Route as AuthImport } from './routes/_auth'
import { Route as UnprotectedIndexImport } from './routes/_unprotected/index'
import { Route as UnprotectedTermsAndConditionImport } from './routes/_unprotected/terms-and-condition'
import { Route as UnprotectedPrivacyPolicyImport } from './routes/_unprotected/privacy-policy'
import { Route as ProtectedDashboardImport } from './routes/_protected/_dashboard'
import { Route as AuthVerifyEmailImport } from './routes/_auth/verify-email'
import { Route as AuthRegisterImport } from './routes/_auth/register'
import { Route as AuthLoginImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordImport } from './routes/_auth/forgot-password'
import { Route as AuthConfirmPasswordImport } from './routes/_auth/confirm-password'
import { Route as ProtectedDashboardDashboardIndexImport } from './routes/_protected/_dashboard/dashboard/index'
import { Route as ProtectedDashboardDashboardSettingsImport } from './routes/_protected/_dashboard/dashboard/settings'
import { Route as ProtectedDashboardDashboardCustomersImport } from './routes/_protected/_dashboard/dashboard/customers'
import { Route as ProtectedDashboardDashboardCoursesImport } from './routes/_protected/_dashboard/dashboard/courses'

// Create/Update Routes

const UnprotectedRoute = UnprotectedImport.update({
  id: '/_unprotected',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedRoute = ProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const UnprotectedIndexRoute = UnprotectedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UnprotectedRoute,
} as any)

const UnprotectedTermsAndConditionRoute =
  UnprotectedTermsAndConditionImport.update({
    id: '/terms-and-condition',
    path: '/terms-and-condition',
    getParentRoute: () => UnprotectedRoute,
  } as any)

const UnprotectedPrivacyPolicyRoute = UnprotectedPrivacyPolicyImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => UnprotectedRoute,
} as any)

const ProtectedDashboardRoute = ProtectedDashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)

const AuthVerifyEmailRoute = AuthVerifyEmailImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

const AuthForgotPasswordRoute = AuthForgotPasswordImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)

const AuthConfirmPasswordRoute = AuthConfirmPasswordImport.update({
  id: '/confirm-password',
  path: '/confirm-password',
  getParentRoute: () => AuthRoute,
} as any)

const ProtectedDashboardDashboardIndexRoute =
  ProtectedDashboardDashboardIndexImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)

const ProtectedDashboardDashboardSettingsRoute =
  ProtectedDashboardDashboardSettingsImport.update({
    id: '/dashboard/settings',
    path: '/dashboard/settings',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)

const ProtectedDashboardDashboardCustomersRoute =
  ProtectedDashboardDashboardCustomersImport.update({
    id: '/dashboard/customers',
    path: '/dashboard/customers',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)

const ProtectedDashboardDashboardCoursesRoute =
  ProtectedDashboardDashboardCoursesImport.update({
    id: '/dashboard/courses',
    path: '/dashboard/courses',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/_unprotected': {
      id: '/_unprotected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UnprotectedImport
      parentRoute: typeof rootRoute
    }
    '/_auth/confirm-password': {
      id: '/_auth/confirm-password'
      path: '/confirm-password'
      fullPath: '/confirm-password'
      preLoaderRoute: typeof AuthConfirmPasswordImport
      parentRoute: typeof AuthImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordImport
      parentRoute: typeof AuthImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof AuthImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof AuthImport
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailImport
      parentRoute: typeof AuthImport
    }
    '/_protected/_dashboard': {
      id: '/_protected/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedDashboardImport
      parentRoute: typeof ProtectedImport
    }
    '/_unprotected/privacy-policy': {
      id: '/_unprotected/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof UnprotectedPrivacyPolicyImport
      parentRoute: typeof UnprotectedImport
    }
    '/_unprotected/terms-and-condition': {
      id: '/_unprotected/terms-and-condition'
      path: '/terms-and-condition'
      fullPath: '/terms-and-condition'
      preLoaderRoute: typeof UnprotectedTermsAndConditionImport
      parentRoute: typeof UnprotectedImport
    }
    '/_unprotected/': {
      id: '/_unprotected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof UnprotectedIndexImport
      parentRoute: typeof UnprotectedImport
    }
    '/_protected/_dashboard/dashboard/courses': {
      id: '/_protected/_dashboard/dashboard/courses'
      path: '/dashboard/courses'
      fullPath: '/dashboard/courses'
      preLoaderRoute: typeof ProtectedDashboardDashboardCoursesImport
      parentRoute: typeof ProtectedDashboardImport
    }
    '/_protected/_dashboard/dashboard/customers': {
      id: '/_protected/_dashboard/dashboard/customers'
      path: '/dashboard/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof ProtectedDashboardDashboardCustomersImport
      parentRoute: typeof ProtectedDashboardImport
    }
    '/_protected/_dashboard/dashboard/settings': {
      id: '/_protected/_dashboard/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof ProtectedDashboardDashboardSettingsImport
      parentRoute: typeof ProtectedDashboardImport
    }
    '/_protected/_dashboard/dashboard/': {
      id: '/_protected/_dashboard/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardDashboardIndexImport
      parentRoute: typeof ProtectedDashboardImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthConfirmPasswordRoute: typeof AuthConfirmPasswordRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthConfirmPasswordRoute: AuthConfirmPasswordRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedDashboardRouteChildren {
  ProtectedDashboardDashboardCoursesRoute: typeof ProtectedDashboardDashboardCoursesRoute
  ProtectedDashboardDashboardCustomersRoute: typeof ProtectedDashboardDashboardCustomersRoute
  ProtectedDashboardDashboardSettingsRoute: typeof ProtectedDashboardDashboardSettingsRoute
  ProtectedDashboardDashboardIndexRoute: typeof ProtectedDashboardDashboardIndexRoute
}

const ProtectedDashboardRouteChildren: ProtectedDashboardRouteChildren = {
  ProtectedDashboardDashboardCoursesRoute:
    ProtectedDashboardDashboardCoursesRoute,
  ProtectedDashboardDashboardCustomersRoute:
    ProtectedDashboardDashboardCustomersRoute,
  ProtectedDashboardDashboardSettingsRoute:
    ProtectedDashboardDashboardSettingsRoute,
  ProtectedDashboardDashboardIndexRoute: ProtectedDashboardDashboardIndexRoute,
}

const ProtectedDashboardRouteWithChildren =
  ProtectedDashboardRoute._addFileChildren(ProtectedDashboardRouteChildren)

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRouteWithChildren
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRouteWithChildren,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface UnprotectedRouteChildren {
  UnprotectedPrivacyPolicyRoute: typeof UnprotectedPrivacyPolicyRoute
  UnprotectedTermsAndConditionRoute: typeof UnprotectedTermsAndConditionRoute
  UnprotectedIndexRoute: typeof UnprotectedIndexRoute
}

const UnprotectedRouteChildren: UnprotectedRouteChildren = {
  UnprotectedPrivacyPolicyRoute: UnprotectedPrivacyPolicyRoute,
  UnprotectedTermsAndConditionRoute: UnprotectedTermsAndConditionRoute,
  UnprotectedIndexRoute: UnprotectedIndexRoute,
}

const UnprotectedRouteWithChildren = UnprotectedRoute._addFileChildren(
  UnprotectedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof ProtectedDashboardRouteWithChildren
  '/confirm-password': typeof AuthConfirmPasswordRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/privacy-policy': typeof UnprotectedPrivacyPolicyRoute
  '/terms-and-condition': typeof UnprotectedTermsAndConditionRoute
  '/': typeof UnprotectedIndexRoute
  '/dashboard/courses': typeof ProtectedDashboardDashboardCoursesRoute
  '/dashboard/customers': typeof ProtectedDashboardDashboardCustomersRoute
  '/dashboard/settings': typeof ProtectedDashboardDashboardSettingsRoute
  '/dashboard': typeof ProtectedDashboardDashboardIndexRoute
}

export interface FileRoutesByTo {
  '': typeof ProtectedDashboardRouteWithChildren
  '/confirm-password': typeof AuthConfirmPasswordRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/privacy-policy': typeof UnprotectedPrivacyPolicyRoute
  '/terms-and-condition': typeof UnprotectedTermsAndConditionRoute
  '/': typeof UnprotectedIndexRoute
  '/dashboard/courses': typeof ProtectedDashboardDashboardCoursesRoute
  '/dashboard/customers': typeof ProtectedDashboardDashboardCustomersRoute
  '/dashboard/settings': typeof ProtectedDashboardDashboardSettingsRoute
  '/dashboard': typeof ProtectedDashboardDashboardIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_unprotected': typeof UnprotectedRouteWithChildren
  '/_auth/confirm-password': typeof AuthConfirmPasswordRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_protected/_dashboard': typeof ProtectedDashboardRouteWithChildren
  '/_unprotected/privacy-policy': typeof UnprotectedPrivacyPolicyRoute
  '/_unprotected/terms-and-condition': typeof UnprotectedTermsAndConditionRoute
  '/_unprotected/': typeof UnprotectedIndexRoute
  '/_protected/_dashboard/dashboard/courses': typeof ProtectedDashboardDashboardCoursesRoute
  '/_protected/_dashboard/dashboard/customers': typeof ProtectedDashboardDashboardCustomersRoute
  '/_protected/_dashboard/dashboard/settings': typeof ProtectedDashboardDashboardSettingsRoute
  '/_protected/_dashboard/dashboard/': typeof ProtectedDashboardDashboardIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/confirm-password'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/privacy-policy'
    | '/terms-and-condition'
    | '/'
    | '/dashboard/courses'
    | '/dashboard/customers'
    | '/dashboard/settings'
    | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/confirm-password'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/verify-email'
    | '/privacy-policy'
    | '/terms-and-condition'
    | '/'
    | '/dashboard/courses'
    | '/dashboard/customers'
    | '/dashboard/settings'
    | '/dashboard'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_unprotected'
    | '/_auth/confirm-password'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/verify-email'
    | '/_protected/_dashboard'
    | '/_unprotected/privacy-policy'
    | '/_unprotected/terms-and-condition'
    | '/_unprotected/'
    | '/_protected/_dashboard/dashboard/courses'
    | '/_protected/_dashboard/dashboard/customers'
    | '/_protected/_dashboard/dashboard/settings'
    | '/_protected/_dashboard/dashboard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  UnprotectedRoute: typeof UnprotectedRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  UnprotectedRoute: UnprotectedRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/_protected",
        "/_unprotected"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/confirm-password",
        "/_auth/forgot-password",
        "/_auth/login",
        "/_auth/register",
        "/_auth/verify-email"
      ]
    },
    "/_protected": {
      "filePath": "_protected.tsx",
      "children": [
        "/_protected/_dashboard"
      ]
    },
    "/_unprotected": {
      "filePath": "_unprotected.tsx",
      "children": [
        "/_unprotected/privacy-policy",
        "/_unprotected/terms-and-condition",
        "/_unprotected/"
      ]
    },
    "/_auth/confirm-password": {
      "filePath": "_auth/confirm-password.tsx",
      "parent": "/_auth"
    },
    "/_auth/forgot-password": {
      "filePath": "_auth/forgot-password.tsx",
      "parent": "/_auth"
    },
    "/_auth/login": {
      "filePath": "_auth/login.tsx",
      "parent": "/_auth"
    },
    "/_auth/register": {
      "filePath": "_auth/register.tsx",
      "parent": "/_auth"
    },
    "/_auth/verify-email": {
      "filePath": "_auth/verify-email.tsx",
      "parent": "/_auth"
    },
    "/_protected/_dashboard": {
      "filePath": "_protected/_dashboard.tsx",
      "parent": "/_protected",
      "children": [
        "/_protected/_dashboard/dashboard/courses",
        "/_protected/_dashboard/dashboard/customers",
        "/_protected/_dashboard/dashboard/settings",
        "/_protected/_dashboard/dashboard/"
      ]
    },
    "/_unprotected/privacy-policy": {
      "filePath": "_unprotected/privacy-policy.tsx",
      "parent": "/_unprotected"
    },
    "/_unprotected/terms-and-condition": {
      "filePath": "_unprotected/terms-and-condition.tsx",
      "parent": "/_unprotected"
    },
    "/_unprotected/": {
      "filePath": "_unprotected/index.tsx",
      "parent": "/_unprotected"
    },
    "/_protected/_dashboard/dashboard/courses": {
      "filePath": "_protected/_dashboard/dashboard/courses.tsx",
      "parent": "/_protected/_dashboard"
    },
    "/_protected/_dashboard/dashboard/customers": {
      "filePath": "_protected/_dashboard/dashboard/customers.tsx",
      "parent": "/_protected/_dashboard"
    },
    "/_protected/_dashboard/dashboard/settings": {
      "filePath": "_protected/_dashboard/dashboard/settings.tsx",
      "parent": "/_protected/_dashboard"
    },
    "/_protected/_dashboard/dashboard/": {
      "filePath": "_protected/_dashboard/dashboard/index.tsx",
      "parent": "/_protected/_dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
